### ISSUE TITLE
npm specifiers have not yet been implemented for this sub command error

### ISSUE THREAD

**Issue by cayblood** [GJZwiers/sentry_deno#14]
Hi! In your README you mention that it should now be possible to import Sentry using the following:
```
import * as Sentry from "npm:@sentry/node";
```

However, when I do this, I get the following error:

```
error: npm specifiers have not yet been implemented for this sub command (https://github.com/denoland/deno/issues/15960). Found: npm:@sentry/node
```

Am I doing something wrong? Thanks in advance for your help.

**Comment by GJZwiers** [comment]
Hello! What is your `deno --version`? Also what command are you using, because npm specifiers are not supported in all `deno` commands yet.

**Comment by cayblood** [comment]
```
∴ deno --version
deno 1.28.3 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.8.3
```

I'm using `deno compile main.ts` inside a simple repository generated from a Deno Deploy playground, just to check my code for bugs before trying to deploy it.

**Comment by GJZwiers** [comment]
Ah, they are not supported in `deno compile` at the moment. According to the [Deno manual](https://deno.land/manual@v1.29.1/node/npm_specifiers#using-npm-packages-with-npm-specifiers):

_These specifiers currently work with deno run, deno check, deno info, deno install, deno lsp, deno repl, deno test, and deno bench, but do not with deno bundle, deno compile and deno vendor at the moment._

**Comment by cayblood** [comment]
I assume that means they also won't work with Deno Deploy? Sorry, I'm new to Deno.

**Comment by GJZwiers** [comment]
They're working on support for Deno Deploy, but I believe it's expected somewhere in Q1 2023
